// Define a mapping of environment variable names to their values
const ENV_VARS = {
    "NEXT_PUBLIC_THEGRAPH_SUBGRAPH_URL": process.env.NEXT_PUBLIC_THEGRAPH_SUBGRAPH_URL,
    "NEXT_PUBLIC_GOLDSKY_SUBGRAPH_URL": process.env.NEXT_PUBLIC_GOLDSKY_SUBGRAPH_URL,
    "NEXT_PUBLIC_ALCHEMY_SUBGRAPH_URL": process.env.NEXT_PUBLIC_ALCHEMY_SUBGRAPH_URL,
    "NEXT_PUBLIC_ENVIO_HYPERINDEX_API_URL": process.env.NEXT_PUBLIC_ENVIO_HYPERINDEX_API_URL,
    "NEXT_PUBLIC_PONDER_GRAPHQL_API_URL": process.env.NEXT_PUBLIC_PONDER_GRAPHQL_API_URL,
    "NEXT_PUBLIC_ALLIUM_WS_URL": process.env.NEXT_PUBLIC_ALLIUM_WS_URL,
    "NEXT_PUBLIC_QUICKNODE_STREAM_WS_URL": process.env.NEXT_PUBLIC_QUICKNODE_STREAM_WS_URL,
    "NEXT_PUBLIC_GOLDSKY_MIRROR_WS_URL": process.env.NEXT_PUBLIC_GOLDSKY_MIRROR_WS_URL,
    "NEXT_PUBLIC_THIRDWEB_INSIGHT_API_URL": process.env.NEXT_PUBLIC_THIRDWEB_INSIGHT_API_URL,
    "NEXT_PUBLIC_MONAD_TESTNET_RPC_URL": process.env.NEXT_PUBLIC_MONAD_TESTNET_RPC_URL,
};

type EnvVarName = keyof typeof ENV_VARS;

const getEnvOrThrow = (env: EnvVarName) => {
    const value = ENV_VARS[env];
    if (!value) {
        throw new Error(`${env} is not set`);
    }
    return value;
};

export const THEGRAPH_SUBGRAPH_URL = getEnvOrThrow("NEXT_PUBLIC_THEGRAPH_SUBGRAPH_URL");
export const GOLDSKY_SUBGRAPH_URL = getEnvOrThrow("NEXT_PUBLIC_GOLDSKY_SUBGRAPH_URL");
export const ALCHEMY_SUBGRAPH_URL = getEnvOrThrow("NEXT_PUBLIC_ALCHEMY_SUBGRAPH_URL");
export const ENVIO_HYPERINDEX_API_URL = getEnvOrThrow("NEXT_PUBLIC_ENVIO_HYPERINDEX_API_URL");
export const PONDER_GRAPHQL_API_URL = getEnvOrThrow("NEXT_PUBLIC_PONDER_GRAPHQL_API_URL");
export const ALLIUM_WS_URL = getEnvOrThrow("NEXT_PUBLIC_ALLIUM_WS_URL");
export const QUICKNODE_STREAM_WS_URL = getEnvOrThrow("NEXT_PUBLIC_QUICKNODE_STREAM_WS_URL");
export const GOLDSKY_MIRROR_WS_URL = getEnvOrThrow("NEXT_PUBLIC_GOLDSKY_MIRROR_WS_URL");
export const THIRDWEB_INSIGHT_API_URL = getEnvOrThrow("NEXT_PUBLIC_THIRDWEB_INSIGHT_API_URL");
export const MONAD_TESTNET_RPC_URL = getEnvOrThrow("NEXT_PUBLIC_MONAD_TESTNET_RPC_URL");
